wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1705212055.85823
    t:
      1:
      - 55
      - 86
      - 95
      - 105
      2:
      - 55
      - 86
      - 95
      - 105
      3:
      - 23
      4: 3.10.13
      5: 0.16.2
      8:
      - 1
      - 5
      9:
        2: langchain
      13: linux-x86_64
